Repository datafusion-contrib/datafusion-table-providers, pull requests merged in 2025-03, with the labels that each got.

#253 Check in Cargo.lock to make builds reproducible
  .gitignore
  Cargo.lock
Labels: dependencies

#288 Switch from Appender to duckdb_arrow_scan
  Cargo.toml
  src/duckdb.rs
  src/duckdb/write.rs
Labels: enhancement

#287 refactor: New TableManager interfaces for DuckDB
  Cargo.toml
  src/duckdb.rs
  src/duckdb/creator.rs
  src/duckdb/write.rs
  src/util/on_conflict.rs
Labels: enhancement

#290 fix: Make an initial table during `TableProviderFactory::create()` for DuckDB
  src/duckdb.rs
  src/duckdb/creator.rs
  src/duckdb/write.rs
Labels: bug
